### ISSUE TITLE
Is it possible to have custom selector UIViewController in storyboard?

### ISSUE THREAD

**Issue by PhilJay** [xmartlabs/XLForm#179]
I have set a custom `selectorControllerClass` for a row in my forms.
The user interface for this ViewController is defined in storyboard. 

But when I klick the form and the selectorControllerClass opens I only see a blank (no UI elements) ViewController.

What could be the issue with this?

**Comment by ageorgios** [comment]
I also have problems with selectorControllerClass
I use:
row.selectorControllerClass = CommandsTableViewController.self;
where CommandsTableViewController is defined in a storyboard and properly registered but I get:
'unable to dequeue a cell with identifier command - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'

**Comment by leberwurstsaft** [comment]
Well, the controller is just allocated and initialized, then `initWithNibName:bundle:` is called, but no nib name is set since the controller wasn't instantiated by the storyboard and all references/identifiers from the storyboard are therefore missing as well.

The quick hack is to override that method in your controller class, check for nil, and return the controller from the storyboard instead.

Much better would be to really embrace storyboards in XLForm, because right now there is also no good way to setup the controller (no prepareForSegue call...).
