### ISSUE TITLE
I download the project. But I can't comply successfully. the tip is below

### ISSUE THREAD

**Issue by duoluo** [xmartlabs/XLForm#230]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by mtnbarreto** [comment]
@duoluo you should run `pod install` from within the project folder and then open the workspace ( `open XLForm.xcworkspace` ) instead of opening the project file.

This is because the example project makes use of some pod libraries to show advance examples.

When you use XLForm in your project, `pod 'XLForm'  :git => 'https://github.com/xmartlabs/XLForm.git'` you will not include these dependencies (cocoapods will only include XLForm source files) since XLForm has not dependencies over other pods.

Regards

**Comment by tciuro** [comment]
@mtnbarreto could you please elaborate on the following:

    When you use XLForm in your project, pod 'XLForm' :git => 'https://github.com/xmartlabs/XLForm.git'
    you will not include these dependencies (cocoapods will only include XLForm source files) since
    XLForm has not dependencies over other pods.

It would be great if the documentation stated how to use XLForm in other projects. Not everyone is well versed in Cocoapods and this extra bit of information would, I'm sure, help other developers in the same position. Thanks!
