### ISSUE TITLE
Pass a parameter to viewControllerClass

### ISSUE THREAD

**Issue by depl0y** [xmartlabs/XLForm#233]
I would love to know if it is possible to pass a variable to either the `init` of the `viewControllerClass`.

For example, I have this row definition:

		row = XLFormRowDescriptor(tag: "ROOMS", rowType: XLFormRowDescriptorTypeSelectorPush) as XLFormRowDescriptor;
		row.title = NSLocalizedString("ROOMS", comment: "Rooms");
		row.value = self.home.rooms.count;
		row.action.viewControllerClass = RoomsViewController.self;
		devicesSection.addFormRow(row);

But the RoomsViewController needs to have a property set, for example the property `room`. When the property `room` is set, the ViewController should go do some more cool stuff, but I can't figure out how to get this done.

I tried changing the type to a `Button` (together with the `action.formBlock`), but then I lose the `detailedTextLabel`, which I would like to use.

Currently, the workaround I am using is the following:

````
	override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
		
		var row = self.form.formRowAtIndex(indexPath);
		if (row.tag == "ROOMS") {
			DDLogVerbose("Clicked row");
			var vc = RoomsViewController(home: self.home);
			self.navigationController?.pushViewController(vc, animated: true);
		}
		else {
			super.tableView(tableView, didSelectRowAtIndexPath: indexPath);
		}
		tableView.deselectRowAtIndexPath(indexPath, animated: true);
	}
````

**Comment by mtnbarreto** [comment]
@depl0y you can set up a segue class apart from the viewControllerClass you are already set up.

what I mean is
`row.action.formSegueClass = NSClassFromString(@"UIStoryboardPushSegue");` then set up the variables you need from `-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender` view controller method.You must call super implementation from your custom form view controller. https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Controllers/XLFormViewController.m#L591

---------------------------------------------------------------------

You can also make use of rowDescriptor property (https://github.com/xmartlabs/XLForm/blob/0977c2cb49f61b137de20e0f26bff3da9ca7de2e/XLForm/XL/Controllers/XLFormRowDescriptorViewController.h) that RoomsViewController should have since it conforms to `XLFormRowDescriptorViewController` protocol. Having the rowDescriptor you can get the sectionDescriptor or even the XLFormViewController and make some of them provide the value rooms view controller are interested in.

---------------------------------------------------------------------

Another solution if you are using storyboards is set up `row.action.formSegueIdenfifier` with the push segue identifier you define though storyboard, then set up the home RoomViewControllers property within `prepareForSegue` method.


These properties i have mentioned ( row.action......  ) are only available on master branch for now.
Hope it helps. If not i can clarify more my answer.

**Comment by cerupcat** [comment]
@mtnbarreto I'm confused on how to do this in code only. Do you have a small example of how to pass in a dictionary (or something else) into the viewController being pushed?
