### ISSUE TITLE
Font 

### ISSUE THREAD

**Issue by marinotws** [xmartlabs/XLForm#260]
How to change font e color for XLFormRowDescriptorTypePicker ?

thanks

**Comment by marinotws** [comment]
help !

**Comment by mtnbarreto** [comment]
@marinotws  
You will have to extend `XLFormPickerCell` implementing `- (NSAttributedString *)pickerView:(UIPickerView *)pickerView attributedTitleForRow:(NSInteger)row forComponent:(NSInteger)component `. This method is part of  `UIPickerViewDelegate` protocol.

Then you need to let the library know that it should use your `XLFormPickerCell` extension instead of base `XLFormPickerCell` implementation by invoking `[[XLFormViewController cellClassesForRowDescriptorTypes][XLFormRowDescriptorTypePicker] = [XLFormPickerCellExtension class]`

Hope it helps!
