### ISSUE TITLE
Is there a way to opt out of XLFormRowNavigationAccessoryView?

### ISSUE THREAD

**Issue by MuscleRumble** [xmartlabs/XLForm#274]
Seems like a new feature, but is there a way to opt out of `XLFormRowNavigationAccessoryView`? It's also overwriting `returnKeyType` of `XLFormTextFieldCell`, which is very unpleasant. Should be fixed in line ~579 of `XLFormViewController.m`.

**Comment by mtnbarreto** [comment]
@MuscleRumble we can disable the input accessory view by overriding `inputAccessoryViewForRowDescriptor:` XLFormViewController method.

```objc
-(UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor
{
      return nil;
}
```

you may want to check the `rowDescriptor` type and enable the inputAccessoryView to only some cells.

You can configure the row navigation by changing `@property (nonatomic) XLFormRowNavigationOptions rowNavigationOptions;` value .  
This will also update the returnKeyType accordingly. 

All possible values are shown in https://github.com/xmartlabs/XLForm/tree/master/Examples/Objective-C/AccessoryViews/AccessoryViewFormViewController.m within example app. 

If the navigation doesn't fit your needs (i mean the configuration values don't work for you because you have a totally uncommon case) you can create your custom navigation overriding: 

```objc
-(XLFormRowDescriptor *)nextRowDescriptorForRow:(XLFormRowDescriptor*)currentRow withDirection:(XLFormRowNavigationDirection)direction;
```

Regarding the returnKeyType value, you will have to override `- (BOOL)textFieldShouldBeginEditing:(UITextField *)textField` XLFormViewController method to customize it.

The approach i suggest to handle all the customizations is make your custom form view controllers extend from a unique base FormViewController instead of extending from `XLFormViewController` directly.  


All the methods i mentioned before are defined here: https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Controllers/XLFormViewController.h#L66

Regards
