### ISSUE TITLE
Issue #256 repost ..not sure if has attention of xsmartlabs - unable to pass data to xlform in a segue

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/XLForm#285]
Hi - Unable to pass data to xlformviewcontroller as a destination viewcontroller via prepareforsegue seems to be fundamental issue as described in issue#256 ...would appreciate  if someone from xsmartlabs can provide guidance on if I am missing something here or provide a workaround.

Thanks in advance.

**Comment by jbasttdi** [comment]
hi,you should invoke     [super prepareForSegue:segue sender:sender];
````
-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender{
    [super prepareForSegue:segue sender:sender];
    if ([segue.identifier isEqualToString:@"tripuser2teamselect"]) {
        TripUserTeamSelectController *destController=segue.destinationViewController;
        destController.tripInfo=_tripInfo;
    }
}
````

**Comment by m-revetria** [comment]
Closing this since it duplicates issue #256.

Please in the future avoid creating duplicated issues. We do our best to fix issues, implementing new features and helping with questions. Duplicating issues only makes the job harder and negative affect the support that we can provide.

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on Stack Overflow and tag `xlform`.

Regards
