### ISSUE TITLE
libPods.a missing?

### ISSUE THREAD

**Issue by sleepybuddha** [xmartlabs/XLForm#307]
Hi there!

Sorry for the maybe noob question but I followed the installation instructions - I even re-tried it 3 times - but every time the libPods.a and XLForm.app is red and build gives this warning:

The file “Pods.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/chris/Documents/Xcode/XLForm/Examples/Objective-C/Pods/Target Support Files/Pods/Pods.debug.xcconfig)

I notice that the \ is missing in the Target\ Support\ Files. Where can I change this?

Thanks!

**Comment by pastorin** [comment]
Hello @sleepybuddha,

The problem is you don't install the cocoapod dependencies running the 'pod install'. 
Follow the steps below:
  1. Open the Terminal
  2. Go to Objective-c example folder 'cd /Users/chris/Documents/Xcode/XLForm/Examples/Objective-C"
  3. Run 'pod install'
  4. Open the file XLForm.xcworkspace - located in the same folder - using XCode and run the project.

Let me know if you have any problems.

Martin
