### ISSUE TITLE
textLabel color customization

### ISSUE THREAD

**Issue by ericcgu** [xmartlabs/XLForm#356]
Is anyone else able to get this to work?  DetailTextLabel works.

row.cellConfigAtConfigure.setObject(UIColor.whiteColor(), forKey: "textLabel.textColor")

**Comment by ericcgu** [comment]
row.cellConfig.setObject(UIColor.whiteColor(), forKey: "textLabel.textColor") works

**Comment by mtnbarreto** [comment]
Hey @ericcgu
`textLabel.textColor` is overridden from [update method](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormBaseCell.m#L73). You should use `cellConfig` or `cellConfigIfDisabled` in this case. 

`cellConfigAtConfigure` is intended to be used to set up properties right after the UITableViewCell `init` method is called. Since XLForm doesn't reuse cells, this only happens once per table cell (form row).

Notice that XLForm calls update method and then it sets all values contained in `cellConfig` and `cellConfigIfDisabled` as you can see [here](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormBaseCell.m#L50).  

Regards

**Comment by ericcgu** [comment]
Thanks, got it.
