### ISSUE TITLE
malformed predicate

### ISSUE THREAD

**Issue by hariseldon78** [xmartlabs/XLForm#370]
With this code: 

    row=[[XLFormRowDescriptor formRowDescriptorWithTag:kCambiaPassword rowType:XLFormRowDescriptorTypeBooleanSwitch title:@"Cambia password:"]defaultFormatting];
    row.value = @0;
    [section addFormRow:row];

    row=[XLFormRowDescriptor formRowDescriptorWithTag:kRefOldPass rowType:XLFormRowDescriptorTypePassword];
    row.value=[Utils unnillify:editingUser.password];
    row.hidden=@(true);
    [section addFormRow:row];
	
    row=[[XLFormRowDescriptor formRowDescriptorWithTag:kVecchiaPassword rowType:XLFormRowDescriptorTypePassword title:@"Vecchia password:" ]defaultFormatting];
    row.hidden=[NSString stringWithFormat:@"!($%@ == 1 && $%@ != '')",kCambiaPassword,kRefOldPass ];
    row.value=@"";
    [section addFormRow:row];
	
    row=[[XLFormRowDescriptor formRowDescriptorWithTag:kNuovaPassword rowType:XLFormRowDescriptorTypePassword title:@"Nuova password:"]defaultFormatting];
    row.hidden=[NSString stringWithFormat:@"!($%@ == 1 AND ($%@ == $%@))",kCambiaPassword,kRefOldPass,kVecchiaPassword];
    [section addFormRow:row];

I get the error: 
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse the format string "!($CambiaPassword.value == 1 AND ($RefOldPass.value == $VecchiaPassword)).value"'

**Comment by hariseldon78** [comment]
Hi. I already narrowed down the problem and found a workaround: if i replace the last string with:
    row.hidden=[NSString stringWithFormat:@"!($%@ == 1 AND ($%@ == $%@ ))",kCambiaPassword,kRefOldPass,kVecchiaPassword];
it starts working and evaluates correctly. So the blank space after the $%@ did the trick!

**Comment by mtnbarreto** [comment]
@hariseldon78 For these kind of "complex" predicates we suggest to set up `hidden` property using a NSPredicate instead of a NSString. 

This is because `XLForm` transforms the NSString to a NSPredicate and sometimes it makes some mistakes, especially for complex predicates. The only advantage of setting up hidden or disable properties using a NSString is that is more readable (we don't need to add `.value` suffix to each row variable). 

Could you please try it out using the following NSPredicate?
`row.hidden= [NSPredicate predicateWithFormat:[NSString stringWithFormat:@"!($%@.value == 1 AND ($%@.value == $%@.value))",kCambiaPassword,kRefOldPass,kVecchiaPassword]];`

Note that I added `.value` suffix after each row variable in the previous line of code.

**Comment by mats-claassen** [comment]
Resolved
