### ISSUE TITLE
formRowDescriptorValueHasChanged not getting called for XLFormRowDescriptorTypeCountDownTimer

### ISSUE THREAD

**Issue by cdstamper** [xmartlabs/XLForm#437]
Related to #330, I'm still having problems with CountDownTimer duration pickers. It seems that I must adjust both hour and minutes, or hour several times, before formRowDescriptorValueHasChanged.

Is there a fix for this? I verified that the commit d67eb7f76238779668bb087b3b0de2992986319d is integrated into my project, and I'm still experiencing the same issue.

**Comment by kotarofujita** [comment]
Yeah. I inquired about the countdown timer a while back which they kindly added. 

This issue seems to affect the date time spinner in general. But its not always consistent. Sometimes, it triggers on one turn and sometimes we need to change the datetime 2 or 3 times before the formRowDescriptorValueHasChanged gets triggered.

**Comment by cdstamper** [comment]
I just submitted a PR that resolves this issue, albeit in a less-than-ideal manner. Seems to be rooted in an iOS bug that was introduced in iOS 7.

**Comment by mats-claassen** [comment]
Working with iOS 8.4 I'am just having this issue when the countdown timer initially nil. Seems that it is an iOS bug.
The simplest workaround would be to set a default value (0 hours 1 min is taken by default if nil).
