### ISSUE TITLE
PopOver reselect row value is nil 

### ISSUE THREAD

**Issue by golfiti** [xmartlabs/XLForm#509]
I need to show old data when re-select selected row

**Comment by mats-claassen** [comment]
Could you be a bit more specific?
Do you mean you want to show the previous value of a row when a user taps twice on it?

**Comment by golfiti** [comment]
![Image of Yaktocat](http://media.giphy.com/media/l41lH1v1Mk9PTv9mM/giphy.gif)

**Comment by mats-claassen** [comment]
Thanks for pointing this out. That happens because the user is deselecting that option.
Actually the same happens with the push selector. 
If you need to change this behaviour, you can use the onChangeBlock to maintain the old value when the row changes to nil or subclass the XLFormSelectorCell class

**Comment by golfiti** [comment]
Thank you Mats.

**Comment by braveS** [comment]
You also could set required property.
[row setRequired:YES];
