### ISSUE TITLE
Unable to set custom autocapitalizationType on textField

### ISSUE THREAD

**Issue by davidrothera** [xmartlabs/XLForm#535]
There are a number of fields that I would like to set autocapitalizationType to `UITextAutocapitalizationType` to `AllCharacters` however when I try and do this with:

```swift
row.cellConfig.setObject(UITextAutocapitalizationType.AllCharacters.rawValue, forKey: "textField.autocapitalizationType")
```

I get an exception:
```
2015-09-02 18:28:05.834 Form Test[69057:22291772] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UITextField 0x7f85c272ce10> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key autocapitalizationType.'
```

Without adding a custom `rowType` is there any other way this could be set manually?

**Comment by mojidabckuu** [comment]
You are not able to setup it because of UITextInput protocol. It seems like Apple provides protocol properties to set values however this type of properties doesn't support KVC protocol and you need to setup it implicitly. Some workaround is to Swizzle methods and replace implementation or try to subclass of row descriptor, but as I understood `XLFormRowDescriptor` class was created without inheritance :(
Anyway, look at `XLFormTextFieldCell.m` at `-(void)update` method. You can find predefined behaviors for different `rowType`.
