### ISSUE TITLE
Side by Side Text Fields

### ISSUE THREAD

**Issue by teevans** [xmartlabs/XLForm#57]
Perhaps shorter text fields for things like city and state and zip, or for an expiration date and cvc code. That would be cool.

**Comment by mtnbarreto** [comment]
@teevans  you can implement it by creating a new custom row. Take a look at the doc: https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row

Since the cell is not used by the native apple forms i would prefer to add this cell within the example project and let the integration decision up to developers.

**Comment by cerupcat** [comment]
@teevans Did you ever implement this?
