### ISSUE TITLE
UISearchController not dismissing when selected after filtering in Example project for Custom Selectors

### ISSUE THREAD

**Issue by lasano** [xmartlabs/XLForm#613]
In iOS9 UISearchController not dismissing after row selection in results controller after performing user filtering in Objective C Example project for Custom Selectors
Issue with UsersTableViewController.m file

**Comment by tommypeps** [comment]
I don´t see UISearchController in Examples 

Screen Shot please

**Comment by lasano** [comment]
https://raw.githubusercontent.com/xmartlabs/XLForm/master/Examples/Objective-C/Examples/Selectors/DynamicSelector/XLForm-dynamic-custom-selector.gif
See the link. This behavior is not working

**Comment by tommypeps** [comment]
@lasano iOS version?

**Comment by lasano** [comment]
I am using XCode 7.0.1 with base sdk iOS 9.0

**Comment by mats-claassen** [comment]
This might have been because the requests were done to a 'http' url which are now being blocked by default. Will change Example project to accept those.

**Comment by riccardo-destefani** [comment]
I have the same issue as @afsalme. 
XCode 8.0 and base sdk 9.0
It's not a 'http' problem, because i hardcoded some data, i'm not loading via http.
When i open popover and i select an item it's all right, but when i open popover, search for an object and then i select an item of the list, popover stay on screen.
in UsersTableViewController.h, didSelectRowAtIndexPath method i have this code, as in @mats-claassen example:
`NSDictionary *dataItem = [self.displayedData objectAtIndex:indexPath.row];
    
    self.rowDescriptor.value = dataItem;
    
    if (self.popoverController){
        [self.popoverController dismissPopoverAnimated:YES];
        [self.popoverController.delegate popoverControllerDidDismissPopover:self.popoverController];
    }
    else if ([self.parentViewController isKindOfClass:[UINavigationController class]]){
        [self.navigationController popViewControllerAnimated:YES];
    }`
but no one of the if statements executes after searching.
