### ISSUE TITLE
Locale not recognized for NSDecimalNumber conversion

### ISSUE THREAD

**Issue by fabidona** [xmartlabs/XLForm#899]
When editing a cell with rowType **XLFormRowDescriptorTypeDecimal** the comma separator, for locales having decimal separator as comma (,) like Euro, is not recognized in NSDecimalNumber conversion from text input. I follow the NSFormatter example for Currency and custom class CurrencyFormatter.

`
row = [XLFormRowDescriptor formRowDescriptorWithTag:kValidationPriceStandard rowType:XLFormRowDescriptorTypeDecimal title:@"Prezzo listino:"];
[row.cellConfigAtConfigure setObject:@(NSTextAlignmentRight) forKey:@"textField.textAlignment"];CurrencyFormatter *numberFormatter = [[CurrencyFormatter alloc] init];
row.valueFormatter = numberFormatter;
row.height = kRowHeight;
`

Below the code snippet with the issue (line 334 in XLFormTextFieldCell.m):

`self.rowDescriptor.value =  [NSDecimalNumber decimalNumberWithString: self.textField.text];`

When I type in the cell for eg. 34,44 with device language and region Italy, it converts to 34 (wrong!) because it not recognize the comma as decimal separator. 

Using the alternative method with locale parameter it works.

`self.rowDescriptor.value =  [NSDecimalNumber decimalNumberWithString: self.textField.text locale:[NSLocale currentLocale]];`

So when I type 34,44 it converts correctly.

**Comment by mats-claassen** [comment]
That has been merged to master branch in #810 

We should get out a new release with the latest fixes.

**Comment by fabidona** [comment]
ok thanks!

**Comment by MatteoMilesi** [comment]
I think this is a partial solution because it only resolves the parsing problem, but it seems to me that there's also a display problem aggravated by the change made.
Eg. If I have Italian locale (comma as separator) and I change the value of the field to 12,34, when it loses focus it displays 12.34 because it shows the `displayText` (XLFormRowDescriptor.m: 203), which returns the object `description` (actually 12.34).
Even if I try to use a formatter to display the number with comma as decimal separator, the field initially displays the correct number, but when I begin editing the comma is replaced by a point (and the next parsing after field loses focus truncates the decimal digits, having @fabidona reverse problem) (12.34 becomes 12).

Locally, I resolved by adding a method `-(NSString*)localizedDisplayText` in XLFormRowDescriptor and replacing the 3 occurrences of `[self.value displayText]` in methods `editTextValue` and `displayTextValue` with it.

Here is the method:
```
-(NSString*)localizedDisplayText
{
    if ([self.rowType isEqualToString:XLFormRowDescriptorTypeNumber] || [self.rowType isEqualToString:XLFormRowDescriptorTypeDecimal])
        return [NSString localizedStringWithFormat:@"%@", self.value];
    else return [self.value displayText];
}
```
