### ISSUE TITLE
Move rows in section programmatically

### ISSUE THREAD

**Issue by Sef1995** [xmartlabs/XLForm#928]
Hi,

I have an action sheet row and a particular value of this row has to trigger a reorder of rows. That means that I have to move some rows upwards in the section and some down. I tried to do this by creating an onChangeBlock on the ActionSheetRow with this code in it to test:
`[self.tableView moveRowAtIndexPath:[NSIndexPath indexPathForRow:1 inSection:0] toIndexPath:[NSIndexPath indexPathForRow:4 inSection:0]];`
but could not get it to work, the row moves but after a split second moves back again to it's old position.

How can I achieve this?

Kind regards,

Sefa

**Comment by mats-claassen** [comment]
That will not work as XLForm's sections have an array of rows in order and when the tableView is reloaded then your row would be back where it was. What needs to be done is to change the order of the rows in the `XLFormSectionDescriptor`. 

The problem is that this is currently not supported. So, there is a function which does exactly that but it is not public. I guess it should be possible to make the function public.

Have a look for `moveRowAtIndexPath:toIndexPath:`

**Comment by Sef1995** [comment]
@mats-claassen Thanks for your reply. I fixed it by doing `[_fields.formRows exchangeObjectAtIndex:1 withObjectAtIndex:2];` in the onChangeBlock.

**Comment by mats-claassen** [comment]
Yeah, but there might still be issues with that as the section has an `formRows` and a `allRows` internally. This is because some rows might be hidden (so they would just be in `allRows`) and you are not reordering the row in that array.

**Comment by Sef1995** [comment]
@mats-claassen Okay, thanks for the heads up. I'll take a look into it.
